# Dependabot will run on day 13 of each month at 01:20 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
    open-pull-requests-limit: 15

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
